"""Static provider contracts for the market ingestion boundary."""

from .baostock import BaoStockDailyBarAdapter, BaoStockProviderAdapter
from .base import (
    ENDPOINT_CONTRACTS,
    AdjustFactorRow,
    AllStockRow,
    AttemptCompletion,
    DailyAStockRow,
    DailyBarProvider,
    DailyFactorRow,
    EndpointContract,
    EndpointContractSummary,
    ExpectedLogicalRequest,
    ExpectedLogicalRequestPlan,
    IndexHistoryRangeRow,
    IndexHistorySessionRow,
    InstrumentRole,
    PaginationPolicy,
    ProviderEndpoint,
    ProviderId,
    ProviderRawBatch,
    ProviderRequest,
    RawEndpointBatch,
    RequestCompletion,
    RequestRole,
    SafeRelativePath,
    SafeVersion,
    TransportLineageRef,
    TransportObservationProjection,
    validate_raw_date_binding,
    validate_safe_relative_path,
)

__all__ = [
    "BaoStockDailyBarAdapter",
    "BaoStockProviderAdapter",
    "AdjustFactorRow",
    "AllStockRow",
    "AttemptCompletion",
    "DailyAStockRow",
    "DailyFactorRow",
    "DailyBarProvider",
    "ENDPOINT_CONTRACTS",
    "EndpointContract",
    "EndpointContractSummary",
    "ExpectedLogicalRequest",
    "ExpectedLogicalRequestPlan",
    "InstrumentRole",
    "IndexHistoryRangeRow",
    "IndexHistorySessionRow",
    "PaginationPolicy",
    "ProviderEndpoint",
    "ProviderId",
    "ProviderRawBatch",
    "ProviderRequest",
    "RequestCompletion",
    "RequestRole",
    "RawEndpointBatch",
    "SafeRelativePath",
    "SafeVersion",
    "TransportLineageRef",
    "TransportObservationProjection",
    "validate_raw_date_binding",
    "validate_safe_relative_path",
]
